-- 无足鸟啊，振翅高飞吧！
name = "群鸟绘卷 · 春󰀜"
version = "9.7"


description =
	"	󰀃当前版本：春雨惊春 " .. version .. "󰀃\n\n" ..
	[[


	春雨惊春 是绘卷的上篇，包含基础运行库。
	绘卷系列的其他模组也必须带这个才能运行。




	󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚󰀚
	󰀬：遇到问题请附日志加Q群 2155066095
																					󰀍
]]

author = "呼吸"
forumthread = ""
api_version = 10
-- 模组图标
-- 授权于作者：https://space.bilibili.com/360207186
-- 图标出处：https://www.bilibili.com/video/BV1Xf4y1N7p1/
icon_atlas = "modicon.xml"
icon = "modicon.tex"
all_clients_require_mod = false
client_only_mod = true
dst_compatible = true
priority = 1000

local function addTitle(title)
	return {
		name = "huxi",
		label = title,
		options = {
			{ description = "", data = 0 },
		},
		default = 0,
	}
end

local function AddOpt(desc, data, hover)
	return { description = desc, data = data, hover = hover }
end

local theKeys = {
	AddOpt("关闭", false),
	AddOpt("B", 98),
	AddOpt("C", 99),
	AddOpt("G", 103),
	AddOpt("H", 104),
	AddOpt("I", 105, "该项是饥荒检查自身皮肤的默认按键, 不怕冲突可以选"),
	AddOpt("J", 106),
	AddOpt("K", 107),
	AddOpt("L", 108),
	AddOpt("N", 110),
	AddOpt("O", 111),
	AddOpt("P", 112),
	AddOpt("R", 114),
	AddOpt("T", 116),
	AddOpt("V", 118),
	AddOpt("X", 120),
	AddOpt("Z", 122),
	AddOpt("减号-", 45),
	AddOpt("加号+", 61),
	AddOpt("鼠标 侧键A", 1005, "不同鼠标可能不生效"),
	AddOpt("鼠标 侧键B", 1006, "不同鼠标可能不生效"),
	AddOpt("关闭", false, " ↑↑↑ 上面不是有关闭按钮嘛 ↑↑↑ ,干嘛要在这里关"),
	AddOpt("<", 44, "小于号或者逗号"),
	AddOpt(">", 46, "大于号或者小数点"),
	AddOpt(":", 59, "冒号或者分号"),
	AddOpt("'", 39, "单引号或者双引号"),
	AddOpt("[", 91, "左括号"),
	AddOpt("]", 93, "右括号"),
	AddOpt("\\", 92, "右斜杠"),
	AddOpt("F1", 282),
	AddOpt("F2", 283),
	AddOpt("F3", 284),
	AddOpt("F4", 285),
	AddOpt("F5", 286),
	AddOpt("F6", 287),
	AddOpt("F7", 288),
	AddOpt("F8", 289),
	AddOpt("F9", 290),
	AddOpt("F10", 291),
	AddOpt("F11", 292),
	AddOpt("方向键(↑)", 273),
	AddOpt("方向键(↓)", 274),
	AddOpt("方向键(←)", 276),
	AddOpt("方向键(→)", 275),
	AddOpt("关闭", false, " ↑↑↑ 上面不是有关闭按钮嘛 ↑↑↑ ,干嘛要在这里关"),
	AddOpt("PageUp", 280, "PageUp"),
	AddOpt("PageDown", 281, "PageDown"),
	AddOpt("Home", 278, "Home"),
	AddOpt("Insert", 277, "Insert"),
	AddOpt("Delete", 127, "Delete"),
	AddOpt("End", 279, "End"),
	AddOpt("Pause", 19, "Pause"),
	AddOpt("Scroll Lock", 145, "Scroll Lock"),
	AddOpt("CAPSLOCK大写锁定", 301, "CAPSLOCK大写锁定"),
	AddOpt("左ALT", 308, "游戏默认的检查键, 请确保不冲突再使用此按键"),
	AddOpt("右ALT", 307, "游戏默认的检查键, 请确保不冲突再使用此按键"),
	AddOpt("左CTRL", 306, "左CTRL"),
	AddOpt("右CTRL", 305, "右CTRL"),
	AddOpt("右Shift", 303, "右Shift"),
	AddOpt("小键盘0", 256, "小键盘0"),
	AddOpt("小键盘1", 257, "小键盘1"),
	AddOpt("小键盘2", 258, "小键盘2"),
	AddOpt("小键盘3", 259, "小键盘3"),
	AddOpt("小键盘4", 260, "小键盘4"),
	AddOpt("小键盘5", 261, "小键盘5"),
	AddOpt("小键盘6", 262, "小键盘6"),
	AddOpt("小键盘7", 263, "小键盘7"),
	AddOpt("小键盘8", 264, "小键盘8"),
	AddOpt("小键盘9", 265, "小键盘9"),
	AddOpt("小键盘 .", 266, "小键盘 ."),
	AddOpt("小键盘 /", 267, "小键盘 /"),
	AddOpt("小键盘 *", 268, "小键盘 *"),
	AddOpt("小键盘 -", 269, "小键盘 -"),
	AddOpt("小键盘 +", 270, "小键盘 +"),
	AddOpt("关闭", false, " ↑↑↑ 上面不是有关闭按钮嘛 ↑↑↑ ,干嘛要在这里关"),
}
local theBoardKeys = { AddOpt("功能面板", "biubiu", "该功能将在功能面板显示") }
for i = 2, #theKeys + 1 do
	theBoardKeys[i] = theKeys[i - 1]
end

local tof = {
	{ description = "开启", data = true, },
	{ description = "关闭", data = false, },
}
local wortox_opt = {}
for i = 0,30 do
	if (i == 12) then
		wortox_opt[i] = {hover = "12可以防止击杀大型boss爆魂",data = i,description=i}
	elseif (i > 20)  then
		wortox_opt[i] = {hover = "超出上限,但是支持某些模组", data = i,description=i}
	else
		wortox_opt[i] = {data = i,description=i,}
	end
end
configuration_options =
{
	addTitle("通用设置"),
	{
		name = "pos_say",
		label = "屏幕提示",
		hover = "游戏中各种消息或语句提示的位置",
		options = {
			{ description = "默认", data = "head", hover = "语句将会出现在人物头顶(仅自己可见)" },
			{ description = "自己的聊天栏", data = "self", hover = "在聊天栏的位置(仅自己可见)" },
			{ description = "宣告出来", data = "ann", hover = "警告：所有人都能看到你的提示消息！" },
			{ description = "关闭", data = false },
		},
		default = "head",
	},
	addTitle("功能面板"),
	{
		name = "sw_mainboard",
		label = "面板绑定",
		hover = "你可以通过点击此键 或 点击屏幕右下方小图标 开启此面板",
		options = theKeys,
		default = 283,
	},
	{
		name = "sw_beauti",
		label = "游戏滤镜",
		hover = "所有滤镜你可以随时开关！",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_shutup",
		label = "去除噪音",
		hover = "包括装备、宠物、建筑、大便、捕鸟器、海浪地皮等各种音效",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_unlock",
		label = "本地指令",
		hover = "解锁图鉴、技能树等",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_cookbook",
		label = "烹饪指南",
		hover = "一本菜谱",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_planthant",
		label = "耕种图鉴",
		hover = "打开耕作先驱",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_nutrients",
		label = "耕作先驱",
		hover = "点击显示土壤肥度等",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_hjsl_unequip",
		label = "装备脱落",
		hover = "设定装备耐久低于多少时自动脱落",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_jh_repair",
		label = "驯牛辅助",
		hover = "若干辅助牛牛的操作",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_newrepair",
		label = "按键修复",
		hover = "按下按键时用指定材料修复指定物品",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_hjsl_repair",
		label = "自动修复",
		hover = "物品耐久低于多少时自动修复",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_autorow",
		label = "自动划船",
		hover = "右键图标进入高级设置可以自行调节速度",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_atreel",
		label = "自动池钓",
		hover = "池钓，右键图标进入高级设置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_fishname",
		label = "自动海钓",
		hover = "辅助拉杆+显示鱼群的名字，右键图标进入高级设置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_autoeat",
		label = "自动吃饭",
		hover = "挂机时启动，自动吃掉食物",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_fishkill",
		label = "自动宰鱼",
		hover = "点击宰杀身上的所有的鱼等生物，右键图标进入高级设置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_watering",
		label = "自动浇灌",
		hover = "填充水壶并自动浇灌作物",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_autowork",
		label = "自动工作",
		hover = "自动进行各种工作",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_wildfires",
		label = "野火警告",
		hover = "提醒正在冒烟的生物或者实体",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_shadowheart",
		label = "雕像制作",
		hover = "自动制作并丢弃雕像",
		options = theBoardKeys,
		default = "biubiu",
	}, 
	{
		name = "sw_hideshell",
		label = "隐藏贝壳",
		hover = "用于帮助寄居蟹打捞贝壳堆",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = 'sw_hideshadow',
		label = "隐藏影怪",
		hover = "游戏内可控制是否显示影怪和攻击影怪",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_nickname",
		label = "昵称显示",
		hover = "房间内其他玩家的头上会显示他们的游戏用户名",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_double",
		label = "队列双击",
		hover = "双击进行批量丢弃和批量转移",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw__keytweak",
		label = "键位提示",
		hover = "提示键位",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_log",
		label = "更新日志",
		hover = "查看本模组的更新日志",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_beebox",
		label = "火中取蜜",
		hover = "点燃蜂箱并拿取蜂蜜",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_drop",
		label = "按键丢弃",
		hover = "快捷键丢弃物品",
		options = theBoardKeys,
		default = "biubiu",
	},
	-- {
	-- 	name = "sw_roll",
	-- 	label = "精确拿取",
	-- 	hover = "【适用于测试服】鼠标滚轮在物品栏上滚动快速拿放物品",
	-- 	options = theBoardKeys,
	-- 	default = "biubiu",
	-- },
	{
		name = "sw_wagstaff",
		label = "静电任务",
		hover = "帮助瓦格斯塔夫做一些任务",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_catcher",
		label = "静电任务+",
		hover = "自动完成静电任务，但是没有瓦格斯塔夫的版本",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_DAG",
		label = "档案馆辅助",
		hover = "携带【蒸馏的知识】或【空白勋章】自动做任务，以及显示任务进度",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_craft",
		label = "制作栏信息",
		hover = "制作栏添加额外的信息显示",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_cane",
		label = "自动切手杖",
		hover = "哦呀？去面板内手动激活吧",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_small",
        label = "小功能绑定",
        hover = "一键开关延迟补偿、快速退出游戏等非常小的功能",
        options = theBoardKeys,
        default = "biubiu",
	},
	{
		name = "sw_space",
		label = "空格过滤器",
		hover = "按下空格不触发对一些物品的动作",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_rescue",
		label = "发送Rescue",
		hover = "按下后会发送/rescue  或者  /救命 \n 该功能用于地下卡海",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_skinHistory",
		label = "历史礼物记录",
		hover = "无需科技开启礼物, 并添加一个【礼物记录】的按钮，记录获得的礼物",
		options = theBoardKeys,
		default = "biubiu",
	},

	addTitle("定制功能"),
	{
		name = "sw_compass",
		label = "指南针",
		hover = "有方向，但没有位置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_mynote",
		label = "我的笔记",
		hover = "简易手册，方便自己查",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_winch",
		label = "打捞定位",
		hover = "正确的位置高亮夹夹绞盘",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_indicator",
		label = "方向指示",
		hover = "为一些重要东西增加箭头指向",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_starfish",
		label = "海星清远古",
		hover = "用于定位生物刷新点",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_tumbleweed",
		label = " 风滚草预测",
		hover = "路过沙漠自动预测风滚草的生成位置（只要圈起来以后就很方便啦）",
		options = theBoardKeys,
		default = "biubiu",
	},


	addTitle("记忆力+"),
	{
		name = "mid_search",
		label = "中键加强",
		hover = "中键点击物品配方，将寻找相关材料，点击物品栏收纳物品",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "sw_autocook1",
		label = "自动烹饪",
		hover = "中键点击锅或按键启动",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "brain_save",
		label = "天亮保存",
		hover = "要不要每天天亮时保存一下数据",
		options = tof,
		default = true,
	},
	{
		name = "brain_sign",
		label = "智能小木牌",
		hover = "打开过的箱子会有小木牌提示里面有什么",
		options = tof,
		default = true,
	},
	{
		name = "brain_bundle",
		label = "打包纸记忆",
		hover = "亲手打包的东西会记得里面有什么",
		options = tof,
		default = true,
	},
	{
		name = "brain_chester",
		label = "箱子物品高亮",
		hover = "鼠标拿起东西或者悬浮在配方上时，高亮物品和箱子",
		options = tof,
		default = true,
	},

	addTitle("呼吸栏"),
	{
		name = "sw_timer",
		label = "功能设置",
		hover = "快捷设置呼吸栏的功能",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "huxi_warn",
		label = "怪物预警",
		hover = "巨鹿，熊大，猎犬等有预警声音提示的倒计时",
		options = tof,
		default = true,
	},
	{
		name = "huxi_clock",
		label = "当前时间",
		hover = "显示当前时间【该功能需要设置里激活】",
		options = tof,
		default = true,
	},
	{
		name = "huxi_pos",
		label = "当前坐标",
		hover = "显示当前坐标【该功能需要设置里激活】",
		options = tof,
		default = true,
	},
	{
		name = "huxi_nightmare",
		label = "暴动 倒计时",
		hover = "地下暴动时间倒计时",
		options = tof,
		default = true,
	},
	{
		name = "huxi_rain",
		label = "降雨 倒计时",
		hover = "降雨时间倒计时",
		options = tof,
		default = true,
	},
	{
		name = "huxi_buff",
		label = "BUFF 倒计时",
		hover = "各种食物的属性倒计时",
		options = tof,
		default = true,
	},
	{
		name = "huxi_boss",
		label = "BOSS 倒计时",
		hover = "各种生物的刷新时间显示",
		options = tof,
		default = true,
	},

	addTitle("地图图标"),
	{
		name = "sw_map",
		label = "功能设置",
		hover = "快捷设置地图图标的功能",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "map_alter",
		label = "定位天体",
		hover = "寻找天体祭坛",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "map_preview",
		label = "地形预览",
		hover = "在选人页面和游戏内查看一些重要资源点",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "map_wormhole",
		label = "虫洞标记",
		hover = "跳跃虫洞后增加虫洞标记",
		options = tof,
		default = true,
	},
	{
		name = "map_gogo",
		label = "自动寻路",
		hover = "点击地图自动到达",
		options = tof,
		default = true,
	},
	{
		name = "map_animal",
		label = "更多生物图标",
		hover = "为常见Boss和生物增加地图图标",
		options = tof,
		default = true,
	},
	{
		name = "map_cavehole",
		label = "洞穴楼梯标记",
		hover = "跨越洞穴和楼梯后增加标记",
		options = tof,
		default = true,
	},

	
	addTitle("右键加强"),
	{
		name = "sw_right",
		label = "右键绑定",
		hover = "右键进行更多操作",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = 'sw_castspell',
		label = "精准施法",
		hover = "唤星唤月等可以在点在猪王屁股上了",
		options = tof,
		default = true,
	},
	{
		name = 'rt_take',
		label = "配方拿取",
		hover = "右键点击配方栏拿取指定数量物品",
		options = tof,
		default = true,
	},
	{
		name = "rt_double",
		label = "双击传送",
		hover = "装备懒狗法杖等装备时，右键传送需要点击两次",
		options = tof,
		default = true,
	},
	{
		name = "sw_autoread",
		label = "自动读书",
		hover = "按住CTRL+右键点击 可以自动阅读书籍（保留一次耐久）",
		options = tof,
		default = true,
	},
	{
		name = "sw_autopush",
		label = "自动推挤",
		hover = "按住SHIFT+右键点击 可以推挤有生命的实体",
		options = tof,
		default = true,
	},
	{
		name = "rt_dirtpile",
		label = "自动翻脚印",
		hover = "右键点击足迹自动翻脚印",
		options = tof,
		default = true,
	},
	{
		name = "sw_butterfly",
		label = "自动抓蝴蝶",
		hover = "启用功能启用后开始抓蝴蝶",
		options = theBoardKeys,
		default = "biubiu",
	},

	addTitle("单项功能"),
	{
		name = "sw_cave",
		label = "洞穴时钟",
		hover = "在洞穴没有光亮的地方也显示时钟",
		options = tof,
		default = true,
	},
	{
		name = "sw_error",
		label = "智能模组",
		hover = "处理报错以及提供日志帮助",
		options = tof,
		default = true,
	},
	{
		name = "sw_mapseed",
		label = "地图种子",
		hover = "创建世界的位置会提示地图种子",
		options = tof,
		default = true,
	},
	{
		name = "sw_multiscreen",
		label = "壁纸模式",
		hover = "在游戏首页上方点击可以查看修改壁纸动画",
		options = tof,
		default = true,
	},
	{
		name = "sw_mySeedTex",
		label = "种子贴图",
		hover = "还原旧版种子贴图",
		options = tof,
		default = true,
	},
	{
		name = "sw_stat",
		label = "状态变化",
		hover = "所有属性栏的变化都会有数字提示出来",
		options = tof,
		default = true,
	},
	{
		name = "sw_wall",
		label = "不要打墙",
		hover = "强制攻击不会打墙和南瓜灯, 除非按住CTRL去点",
		options = {
			{description = "开启", data = true, hover = "还包括不会攻击无敌状态的编织者"},
			{description = "关闭", data = false},
		},
		default = true,
	},
	{
		name = "sw_tele",
		label = "传送标记",
		hover = "传送走生物后原地留下一个位置标记",
		options = tof,
		default = true,
	},
	{
		name = "sw_folder",
		label = "模组目录",
		hover = "在模组名下方显mod存放目录",
		options = tof,
		default = true,
	},
	{
		name = "sw_pinyin",
		label = "拼音搜索",
		hover = "制作栏将支持拼音搜索（首字母或全拼）",
		options = tof,
		default = true,
	},
	{
		name = "sw_showhkit",
		label = "浅海显示",
		hover = "拿起码头地皮时，将显示周围的浅海区域",
		options = tof,
		default = true,
	},
	{
		name = "skinqueue_plus",
		label = "重复皮肤分解",
		hover = "添加一个【分解重复皮肤】的按钮，帮助获得线轴",
		options = tof,
		default = true,
	},
	{
		name = "sw_skinpreset",
		label = "皮肤预设套装",
		hover = "在查看角色皮肤页面，可以直接穿套装",
		options = tof,
		default = true,
	},
	{
		name = "sw_suggest",
		label = "礼包购买建议",
		hover = "在商城购买礼物时，用大白话给出建议",
		options = tof,
		default = true,
	},
	{
		name = 'sw_peopleNum',
		label = "增加人数上限",
		hover = "创建世界时最多可选的人数, 点击应用才能生效",
		options = {
			{description = "开启", data = 6, hover = "开了或者关了都是默认的6人, 默认打开是为了和上面对齐, 图好看"},
			{description = "关闭", data = false, hover = "关了也是默认的6人, 不做任何修改"},
			{description = "8人", data = 8, hover = "记得去创建世界的那里修改人数"},
			{description = "12人", data = 12, hover = "记得去创建世界的那里修改人数"},
			{description = "16人", data = 16, hover = "记得去创建世界的那里修改人数"},
			{description = "24人", data = 24, hover = "记得去创建世界的那里修改人数"},
			{description = "36人", data = 36, hover = "记得去创建世界的那里修改人数"},
			{description = "50人", data = 50, hover = "嚯, 哥们你这配置多少钱一斤啊~"},
			{description = "100人", data = 100, hover = "你是故意来找茬的吧！"},
		},
		default = 6,
	},
	{
		name = 'sw_modplayer',
		label = "模组角色图标",
		hover = "是否在创建世界页面显示你游玩的模组角色图标",
		options = tof,
		default = true,
	},


	addTitle("我的世界"),
	{
		name = "sw_server",
		label = "快速重连",
		hover = "快速重连 的开关设置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "server_login",
		label = "确保登录",
		hover = "保证不会出现游戏内没皮肤的现象。代价是快速重连的速度变慢...",
		options = tof,
		default = true,
	},
	{
		name = "server_reco",
		label = "优先连接方式",
		hover = "注意：wegame不支持IP直连",
		options = {
			{description = "模拟直连", data = "sim", hover = "速度比下面这个选项慢一点，但是胜在稳定"},
			{description = "IP直连", data = "ip", hover = "如果你经常玩云服或者专服，请选择此选项"},
		},
		default = "ip",
	},
	{
		name = "server_server",
		label = "主菜单-服务器",
		hover = "在主菜单增加【服务器】按钮",
		options = tof,
		default = true,
	},
	{
		name = "server_quick",
		label = "主菜单-快速重连",
		hover = "在主菜单增加【快速重连】按钮",
		options = tof,
		default = true,
	},
	{
		name = "server_popup",
		label = "登录页面-快速重连",
		hover = "在登录页面增加【快速重连】按钮",
		options = tof,
		default = true,
	},



	addTitle("范围显示"),
	{
		name = "range_board",
		label = "范围显示",
		hover = "范围显示 的绑定设置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "range_attack",
		label = "攻击范围",
		hover = "是否显示攻击范围",
		options = tof,
		default = true,
	},
	{
		name = "range_player",
		label = "远程范围",
		hover = "玩家手持远程武器或者钓鱼竿时显示玩家自己的对应范围",
		options = tof,
		default = true,
	},
	{
		name = "range_hover",
		label = "悬浮范围",
		hover = "鼠标移动到书籍、火药等部分实体上显示范围",
		options = tof,
		default = true,
	},
	{
		name = "range_click",
		label = "点击范围",
		hover = "鼠标点击水中木、投石机等实体上时显示范围",
		options = tof,
		default = true,
	},
	{
		name = "range_placer",
		label = "放置范围",
		hover = "放置避雷针、眼球炮台等建筑时是否显示范围",
		options = tof,
		default = true,
	},
	{
		name = "animal_track",
		label = "足迹指引",
		hover = "可疑的脚印会有游动的箭头提示狩猎方向",
		options = tof,
		default = true,
	},
	{
		name = "range_search",
		label = "宝物指示器",
		hover = "对各种宝石或别的“宝物”增加一个脚下的箭头",
		options = tof,
		default = true,
	},


	addTitle("物品管理器"),
	{
		name = "ex_board",
		label = "物品管理",
		hover = "决定如何打开管理器的设置",
		options = theBoardKeys,
		default = "biubiu",
	},
	{
		name = "ex_re_equip",
		label = "补充装备",
		hover = "武器、魔杖等耐久用完后会自动拿下一把",
		options = tof,
		default = true,
	},
	{
		name = "ex_re_ammo",
		label = "补充弹药",
		hover = "弹弓、刮地皮头盔等自动补充内容物",
		options = tof,
		default = true,
	},
	{
		name = "cd_skeleton",
		label = "骨甲计时",
		hover = "骨头盔甲增加冷却CD的蓝色圆显示",
		options = tof,
		default = true,
	},
	{
		name = "sw_skeleton",
		label = "骨甲自切",
		hover = "骨头盔甲受击后自动切换CD最短的下一个",
		options = tof,
		default = true,
	},
	{
		name = "text_cd",
		label = "冷却时间",
		hover = "对于旺达的表、骨头盔甲等有CD的物品显示冷却时间",
		options = tof,
		default = true,
	},
	{
		name = "sw_autosort",
        label = "物品整理",
        hover = "按下此键 自动分类并整理所有物品\n【请启用功能面板查看高级设置！】",
        options = theKeys,
        default = 127,
	},

	addTitle("视角变换"),
	{
		name = "sw_C",
		label = "开关",
		hover = "视角变换 的总开关",
		options = tof,
		default = true,
	},
	{
		name = "c_add",
		label = "视野增加",
		hover = "增大视野的快捷键",
		options = theKeys,
		default = 61,
	},
	{
		name = "c_minus",
		label = "视野缩小",
		hover = "减小视野的快捷键",
		options = theKeys,
		default = 45,
	},
	{
		name = "c_hidehud",
		label = "隐藏HUD",
		hover = "隐藏HUD的快捷键",
		options = theKeys,
		default = 291,
	},
	{
		name = "c_hideself",
		label = "隐藏玩家",
		hover = "隐藏玩家的快捷键",
		options = theKeys,
		default = false,
	},
	{
		name = "c_track",
		label = "视角追踪",
		hover = "将视角放置到鼠标下的实体或位置上",
		options = theKeys,
		default = 111,
	},
	{
		name = "c_back",
		label = "视角回切",
		hover = "在自身与最近选定的实体/位置间切换 的快捷键",
		options = theKeys,
		default = 104,
	},
	{
		name = "c_change",
		label = "视角变换",
		hover = "默认/大视野/俯视 的快捷键",
		options = theKeys,
		default = false,
	},
	{
		name = "change_mode",
		label = "变换模式",
		hover = "上面那个视角变换的模式",
		options = {
			{ description = "默认-大视野-俯视", data = 1 },
			{ description = "默认-大视野", data = 2, },
			{ description = "默认-俯视", data = 3, },
			{ description = "大视野-俯视", data = 4, },
		},
		default = 1,
	},
	{
		name = "c_init",
		label = "默认视角",
		hover = "进入游戏时的视角",
		options = {
			{ description = "默认", data = false, hover = "进入游戏时视角默认" },
			{ description = "大视野", data = true, hover = "进入游戏时就启动大视野" },
		},
		default = false,
	},

	addTitle("旺达辅助"),
	{
		name = "sw_wanda",
		label = "开关",
		hover = "旺达辅助的 总开关",
		options = tof,
		default = true,
	},
	{
		name = "pocketwatch_heal",
		label = "激活不老表",
		hover = "不灭钻石：激活一个可用的【不老表】",
		options = theKeys,
		default = 120,
	},
	{
		name = "pocketwatch_warp",
		label = "激活倒走表",
		hover = "白金之星：激活一个可用的【倒走表】",
		options = theKeys,
		default = 114,
	},
	{
		name = "pocketwatch_recall",
		label = "激活溯源表",
		hover = "黄金体验：激活一个可用的【溯源表】",
		options = theKeys,
		default = false,
	},
}
